---
title: "Class 13"
author: "Lindsey Carothers"
date: "2026-10-07"
output: 
  html_document:
    toc: true
    toc_float: true
    code_download: true
    code_folding: show
    theme: simplex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Plane Crash

```{r}
year = 2025

crash_url = paste0('https://www.planecrashinfo.com/', year, '/', year, '.htm')

crash_page <- rvest::read_html(crash_url, encoding = "ISO-8859-1")

# if we were to read this as an html table, I have no control on what goes into each column in the resulting data frame
  # that makes cleaning it more challenging

crash_page |> #column 1
  rvest::html_elements("td:nth-child(1) > font > a") |> 
  rvest::html_text2() -> dates

crash_page |> #column 2
  rvest::html_elements("td:nth-child(2) > font ") |> 
  rvest::html_text2() -> loc_op

crash_page |> 
  rvest::html_elements("td:nth-child(4) > font ") |> 
  rvest::html_text2() -> fatalities

df = data.frame(dates = dates, fatalities = fatalities[-1], loc = loc_op[-1]) |> 
  tidyr::separate(
    loc, into = c("location", "operator"), 
    sep = "\n") |> 
   tidyr::separate(
    fatalities, into = c("plane_fatalities", "passengers", "ground_fatalities"))
```










